### ISSUE TITLE
gitType in tree

### ISSUE THREAD

**Issue by alanshaw** [ipld/js-ipld-git#22]
`tree` expects the node to always have a `gitType` but in the test data I'm working with (`z8mWaJHXieAVxxLagBpdaNWFEBKVWmMiE`) not all the linked objects have that property?

Is the test data incorrect?

**Comment by daviddias** [comment]
@magik6k you are our resident Git IPLD expert, could you answer @alanshaw's question?

**Comment by magik6k** [comment]
`gitType` is only set for commits/tags (to `commit`/`tag` string). Blobs are represented by a js blob. For tree objects it's either not present or it's an object (like other tree entries).

Doesn't `default` switch case work for that: https://github.com/ipld/js-ipld-git/blob/master/src/resolver.js#L126?

**Comment by alanshaw** [comment]
This turned out to be a problem in the code I'm using not an issue here. Sorry!
